AWSTemplateFormatVersion: "2010-09-09"

Description:
  A template for creating a NAT gateway, Elastic public ip, a route table and a mapping for two private subnets

Resources:

  EIPA:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc

  EIPB:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc        

  NATGWA:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId:
          Fn::GetAtt:
          - EIPA
          - AllocationId
        SubnetId: !ImportValue vpc-subnet-weba
        Tags:
        - Key: Name
          Value: Nat-Gateway-A

  NATGWB:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId:
          Fn::GetAtt:
          - EIPB
          - AllocationId
        SubnetId: !ImportValue vpc-subnet-webb
        Tags:
        - Key: Name
          Value: Nat-Gateway-B        

  VpcRouteTableA:
      Type: AWS::EC2::RouteTable
      DependsOn: NATGWA
      Properties: 
        Tags: 
          - Key: Name
            Value: vpc-private-rt-A
        VpcId: !ImportValue vpc

  VpcRouteTableB:
      Type: AWS::EC2::RouteTable
      DependsOn: NATGWB
      Properties: 
        Tags: 
          - Key: Name
            Value: vpc-private-rt-B
        VpcId: !ImportValue vpc

  RouteA:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Ref: VpcRouteTableA
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NATGWA

  RouteB:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Ref: VpcRouteTableB
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NATGWB

  SubnetRouteATableAssoc1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
          RouteTableId: !Ref VpcRouteTableA
          SubnetId: !ImportValue vpc-subnet-dba

  SubnetRouteATableAssoc2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
          RouteTableId: !Ref VpcRouteTableA
          SubnetId: !ImportValue vpc-subnet-appa

  SubnetRouteBTableAssoc1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
          RouteTableId: !Ref VpcRouteTableB
          SubnetId: !ImportValue vpc-subnet-dbb

  SubnetRouteBTableAssoc2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
          RouteTableId: !Ref VpcRouteTableB
          SubnetId: !ImportValue vpc-subnet-appb